
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMEstudiantes = new javax.swing.JMenu();
        jMAAgregar = new javax.swing.JMenuItem();
        jMAConsultar = new javax.swing.JMenuItem();
        jMAListar = new javax.swing.JMenuItem();
        jMProfesores = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMDListar = new javax.swing.JMenuItem();
        jMCursos = new javax.swing.JMenu();
        jMCAgregar = new javax.swing.JMenuItem();
        jMCListar = new javax.swing.JMenuItem();
        jMMatriculas = new javax.swing.JMenu();
        jMMAgregar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/curso.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(320, 228));
        jLabel1.setMinimumSize(new java.awt.Dimension(320, 228));
        jLabel1.setPreferredSize(new java.awt.Dimension(320, 255));

        jMEstudiantes.setText("Estudiantes");
        jMEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMEstudiantes.setPreferredSize(new java.awt.Dimension(85, 26));

        jMAAgregar.setText("Agregar");
        jMAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAAgregarActionPerformed(evt);
            }
        });
        jMEstudiantes.add(jMAAgregar);

        jMAConsultar.setText("Consultar");
        jMAConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAConsultarActionPerformed(evt);
            }
        });
        jMEstudiantes.add(jMAConsultar);

        jMAListar.setText("Listar");
        jMAListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAListarActionPerformed(evt);
            }
        });
        jMEstudiantes.add(jMAListar);

        jMenuBar1.add(jMEstudiantes);

        jMProfesores.setText("Profesores");
        jMProfesores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMProfesores.add(jMenuItem3);

        jMDListar.setText("Listar");
        jMDListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDListarActionPerformed(evt);
            }
        });
        jMProfesores.add(jMDListar);

        jMenuBar1.add(jMProfesores);

        jMCursos.setText("Cursos");
        jMCursos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMCAgregar.setText("Agregar");
        jMCAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAgregarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCAgregar);

        jMCListar.setText("Listar");
        jMCListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCListarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCListar);

        jMenuBar1.add(jMCursos);

        jMMatriculas.setText("Matriculas");
        jMMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMMAgregar.setText("Agregar");
        jMMAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMAgregarActionPerformed(evt);
            }
        });
        jMMatriculas.add(jMMAgregar);

        jMenuBar1.add(jMMatriculas);

        jMenu5.setText("Cerrar");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu5.add(jMSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAAgregarActionPerformed
        // TODO add your handling code here:
        FrmAgregarEstudiante frm = new FrmAgregarEstudiante();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAAgregarActionPerformed

    private void jMAListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAListarActionPerformed
        // TODO add your handling code here:
        FrmListarEstudiantes frm = new FrmListarEstudiantes();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAListarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FrmAgregarProfesor frm = new FrmAgregarProfesor();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMDListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDListarActionPerformed
        // TODO add your handling code here:
        FrmListarProfesores frm = new FrmListarProfesores();
        frm.setVisible(true);
    }//GEN-LAST:event_jMDListarActionPerformed

    private void jMCAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAgregarActionPerformed
        // TODO add your handling code here:
        FrmAgregarCurso frm = new FrmAgregarCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_jMCAgregarActionPerformed

    private void jMCListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCListarActionPerformed
        // TODO add your handling code here:
        FrmListarCursos frm = new FrmListarCursos();
        frm.setVisible(true);
    }//GEN-LAST:event_jMCListarActionPerformed

    private void jMAConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAConsultarActionPerformed
        // TODO add your handling code here:
        FrmConsultarEstudiante frm = new FrmConsultarEstudiante();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAConsultarActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
     int confirmado = JOptionPane.showConfirmDialog(null, "Está seguro de Salir");
     if (JOptionPane.OK_OPTION==confirmado){
         System.exit(0);
     }
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMMAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMAgregarActionPerformed
        // TODO add your handling code here:
        FrmMatricula frm = new FrmMatricula();
        frm.setVisible(true);
    }//GEN-LAST:event_jMMAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMAAgregar;
    private javax.swing.JMenuItem jMAConsultar;
    private javax.swing.JMenuItem jMAListar;
    private javax.swing.JMenuItem jMCAgregar;
    private javax.swing.JMenuItem jMCListar;
    private javax.swing.JMenu jMCursos;
    private javax.swing.JMenuItem jMDListar;
    private javax.swing.JMenu jMEstudiantes;
    private javax.swing.JMenuItem jMMAgregar;
    private javax.swing.JMenu jMMatriculas;
    private javax.swing.JMenu jMProfesores;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
